### PR TITLE
修改了previewResolution的实现，选择手机支持的跟设置最接近的值

### PR DESCRIPTION
**Pull request by microjixl**
修改setPreviewResolution不支持动态修改。修改选择最接近手机支持的PreviewResolution。否则在有些手机上不能正常工作.

 Changes to be committed:
	modified:   library/src/main/java/net/ossrs/yasea/SrsCameraView.java
	modified:   library/src/main/java/net/ossrs/yasea/SrsPublisher.java

### CODE REVIEW

**Comment by begeekmyfriend** [comment]
Your PR is too complicated for me to accept. It will expand the size of source code and hard to maintain in the future. In fact, I do accept minimum changes unless you can point out that there are structural problems in my project.

**Comment by microjixl** [comment]
master branch set SrsCameraView's preview resolution with SrsEncoder's default vPreWidth=1280 and vPreHeight=720 In SrsPublisher constructor. And only change encoder‘s preview resolution when invoke mPublisher.setPreviewResolution(*,*).  Actually SrsCameraView always use 1280*720 resolution. My PR changes SrsCameraView's preview and SrsEncoder's preview to same in SrsPublisher's setPreviewResolution(). if camera not support set values, i will select the resolution which nearest to set value from camera supports resolutions,

**Comment by begeekmyfriend** [comment]
I have got your idea. But the code of your PR is not simple enough. No need to change so many things.

**Comment by microjixl** [comment]
yeah, i am sorry to format code by android studio, that makes some useless changes.  i will delete Resolution. should i delete auto select support preview ?

**Comment by begeekmyfriend** [comment]
You may not. Just keep the `getBestCameraResolution` function and I will merge it.

**Comment by microjixl** [comment]
hey，I change my code and request a new PR #220  as your branch has changed after #218 
thanks!

**Comment by microjixl** [comment]
link to #220

**Pull request closed without merging**
